---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-ex-dev
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/karthikjeeyar/nodejs-ex-gitops.git
    targetRevision: HEAD
    path: ./helm/app
    helm:
      valueFiles:
        - Values.yaml
      values: |
        # Override namespace for dev
        app:
          namespace: nodejs-ex-dev
        image:
          tag: latest
        # Add dev-specific overrides here
  destination:
    server: https://kubernetes.default.svc
    namespace: nodejs-ex-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m